apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: "0.25"
      memory: "1024Mi"
    defaultRequest:
      cpu: "0.25"
      memory: "512Mi"
    type: Container